// Random name generators for usernames and design names

const USERNAME_ADJECTIVES = [
  "Cosmic",
  "Neon",
  "Groovy",
  "Radiant",
  "Electric",
  "Mystic",
  "Vivid",
  "Swirling",
  "Trippy",
  "Stellar",
  "Prism",
  "Blazing",
  "Lucid",
  "Spiral",
  "Funky",
  "Dazzle",
  "Sunset",
  "Aurora",
  "Crystal",
  "Velvet",
  "Dreamy",
  "Astral",
  "Rainbow",
  "Psyche",
  "Vapor",
  "Zen",
  "Wild",
  "Deep",
  "Bright",
];

const USERNAME_NOUNS = [
  "Spinner",
  "Dyer",
  "Weaver",
  "Artist",
  "Crafter",
  "Roller",
  "Wizard",
  "Mixer",
  "Swirler",
  "Painter",
  "Creator",
  "Dreamer",
  "Spider",
  "Maker",
  "Vortex",
  "Phoenix",
  "Tiger",
  "Wolf",
  "Fox",
  "Hawk",
  "Raven",
  "Lotus",
  "Flame",
  "Storm",
  "Wave",
  "Spark",
  "Comet",
  "Orbit",
  "Echo",
  "Pulse",
];

export function generateUsername(): string {
  const adj =
    USERNAME_ADJECTIVES[Math.floor(Math.random() * USERNAME_ADJECTIVES.length)];
  const noun =
    USERNAME_NOUNS[Math.floor(Math.random() * USERNAME_NOUNS.length)];
  const num = Math.floor(Math.random() * 100);
  return `${adj}${noun}${num}`;
}

// Design name word pools, escalating with rarity
const DESIGN_PREFIXES: Record<string, string[]> = {
  common: [
    "Classic",
    "Simple",
    "Warm",
    "Soft",
    "Cool",
    "Fresh",
    "Clean",
    "Mellow",
    "Gentle",
    "Calm",
    "Easy",
    "Light",
    "Pastel",
    "Earthy",
    "Faded",
  ],
  uncommon: [
    "Bold",
    "Vivid",
    "Bright",
    "Deep",
    "Rich",
    "Electric",
    "Vibrant",
    "Striking",
    "Radiant",
    "Gleaming",
    "Lustrous",
    "Saturated",
    "Intense",
  ],
  rare: [
    "Prismatic",
    "Iridescent",
    "Shimmering",
    "Luminous",
    "Opalescent",
    "Chromatic",
    "Spectral",
    "Dazzling",
    "Resplendent",
    "Effervescent",
  ],
  legendary: [
    "Celestial",
    "Transcendent",
    "Ethereal",
    "Mythical",
    "Divine",
    "Arcane",
    "Supernova",
    "Infinite",
    "Astral",
    "Empyrean",
  ],
  mythic: [
    "Omnichrome",
    "Hyperdimensional",
    "Singularity",
    "Primordial",
    "Godweave",
    "Cosmogenesis",
    "Eternium",
    "Voidbloom",
    "Nexus",
  ],
};

const DESIGN_SUFFIXES = [
  "Vortex",
  "Spiral",
  "Bloom",
  "Wave",
  "Cascade",
  "Ripple",
  "Burst",
  "Fusion",
  "Weave",
  "Tide",
  "Pulse",
  "Nebula",
  "Storm",
  "Flame",
  "Drift",
  "Flow",
  "Swirl",
  "Aurora",
  "Ember",
  "Mirage",
  "Echo",
  "Prism",
  "Flare",
  "Haze",
  "Blaze",
  "Glow",
  "Mist",
  "Whirl",
];

export function generateDesignName(rarity: string): string {
  const prefixes = DESIGN_PREFIXES[rarity] || DESIGN_PREFIXES.common;
  const prefix = prefixes[Math.floor(Math.random() * prefixes.length)];
  const suffix =
    DESIGN_SUFFIXES[Math.floor(Math.random() * DESIGN_SUFFIXES.length)];
  return `${prefix} ${suffix}`;
}
